Rename R/Untitled.R to R/vignettes/Untitled.R
move Untitled.R to vignettes so that package can be installed

(getting error:
``` Error in .install_package_code_files(".", instdir) :
files in '/tmp/RtmpqT0h4z/R.INSTALL1ef4cd48d4b/PermafrostTools/R' missing from 'Collate' field:
  Untitled.R
ERROR: unable to collate and parse R files for package ‘PermafrostTools’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/PermafrostTools’
```